### ISSUE TITLE
Output Mapreduce

### ISSUE THREAD

**Issue by whabada** [whabada/hugo#10]
MapReduce erstellt sein Output in der file "part-r-0000". Wie soll dies als Input für die Outputgenerierung dienen? In welchem Format sollte das Output des MR Jobs gespeichert werden?

**Comment by Meier-Andre** [comment]
Der Output (Durschnittsfarbe) von jedem Image soll ja in ne HBase Tabelle geschrieben werden. Die Funktion gibt es auch schon in der HBase Klasse. Ist es möglich, diese in dem Map Reduce Job aufzurufen?

**Comment by whabada** [comment]
der MR Job speichert seine ReducerOutputwerte nun in Hbase
