### ISSUE TITLE
Outputimage hat eine Verschiebung bei der Farbe

### ISSUE THREAD

**Issue by Meier-Andre** [whabada/hugo#4]
Wenn ein Outputimage aus den HBase Daten erstellt wird, entsprechen die Farben nicht den Farben, welche in HBase stehen. 
Beispiel Daten sind Bilder mit alle einer schwarzen Durchschnittsfarbe. Das zusammengesetzte Bild am ende ist aber rot.

**Comment by whabada** [comment]
Erledigt und Closed.
